import streamlit as st
import pandas as pd
import io
from transformers import pipeline

# --- Title and Intro ---
st.title("💹 Finance Report AI Generator")
st.write("Upload your financial data and get instant insights generated by AI.")

# --- Upload Section ---
uploaded_file = st.file_uploader("Upload an Excel or CSV file", type=["csv", "xlsx"])

if uploaded_file:
    try:
        if uploaded_file.name.endswith('.csv'):
            df = pd.read_csv(uploaded_file)
        else:
            df = pd.read_excel(uploaded_file)
        
        st.subheader("🧾 Data Preview")
        st.dataframe(df.head())

        # --- Generate Statistical Summary ---
        st.subheader("📈 Summary Report")
        summary_stats = df.describe()
        st.write(summary_stats)

        # --- Convert Summary to Downloadable Excel ---
        buffer = io.BytesIO()
        with pd.ExcelWriter(buffer, engine='xlsxwriter') as writer:
            summary_stats.to_excel(writer, sheet_name='Summary')
        st.download_button(
            label="Download Excel Report",
            data=buffer.getvalue(),
            file_name="Finance_Report.xlsx",
            mime="application/vnd.ms-excel"
        )

        # --- AI Interpretation Section ---
        st.subheader("🤖 AI-Generated Insights")

        # Prepare short textual summary for the model
        summary_text = f"Here are financial summary statistics: {summary_stats.to_string()}. Please explain what this data indicates in simple, insightful financial terms."

        # Load the model (small version for free usage)
        summarizer = pipeline("text2text-generation", model="google/flan-t5-base")

        # Generate AI response
        with st.spinner("Analyzing your report with AI..."):
            ai_response = summarizer(summary_text, max_length=200)[0]['generated_text']

        # Display AI output
        st.success("AI Interpretation:")
        st.write(ai_response)

    except Exception as e:
        st.error(f"Error reading file: {e}")
else:
    st.info("📤 Please upload a file to generate report and AI insights.")


    except Exception as e:
        st.error(f"Error reading file: {e}")
else:
    st.info("Please upload a file to generate your report.")
